# Copyright 2025 Liam White
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is a .goreleaser.yml file for the worktree project
# Make sure to check the documentation at https://goreleaser.com

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: worktree
    main: ./main.go
    binary: wt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.FullCommit}}
      - -X main.date={{.Date}}

archives:
  - id: worktree
    ids: [worktree]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: liamawhite
    name: worktree
  footer: |
    ## Installation

    ### Download Binary

    Choose the appropriate binary for your platform from the assets below:

    #### Linux (x86_64)
    ```bash
    curl -L https://github.com/liamawhite/worktree/releases/download/{{ .Tag }}/worktree_Linux_x86_64.tar.gz | tar xz
    chmod +x wt
    sudo mv wt /usr/local/bin/
    ```

    #### Linux (ARM64)
    ```bash
    curl -L https://github.com/liamawhite/worktree/releases/download/{{ .Tag }}/worktree_Linux_arm64.tar.gz | tar xz
    chmod +x wt
    sudo mv wt /usr/local/bin/
    ```

    #### macOS (Intel)
    ```bash
    curl -L https://github.com/liamawhite/worktree/releases/download/{{ .Tag }}/worktree_Darwin_x86_64.tar.gz | tar xz
    chmod +x wt
    sudo mv wt /usr/local/bin/
    ```

    #### macOS (Apple Silicon)
    ```bash
    curl -L https://github.com/liamawhite/worktree/releases/download/{{ .Tag }}/worktree_Darwin_arm64.tar.gz | tar xz
    chmod +x wt
    sudo mv wt /usr/local/bin/
    ```

    #### Windows (PowerShell)
    ```powershell
    Invoke-WebRequest -Uri "https://github.com/liamawhite/worktree/releases/download/{{ .Tag }}/worktree_Windows_x86_64.zip" -OutFile "worktree.zip"
    Expand-Archive -Path "worktree.zip" -DestinationPath "."
    # Move wt.exe to a directory in your PATH
    ```

    ### Verify Installation
    ```bash
    wt --version
    ```

    ### Verification with Checksums
    Download `checksums.txt` and verify your binary:
    ```bash
    # Linux/macOS
    sha256sum -c checksums.txt

    # Windows
    certutil -hashfile wt.exe SHA256
    ```

    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
