# Copyright 2025 Liam White
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is a .goreleaser.yml file for the worktree project
# Make sure to check the documentation at https://goreleaser.com

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: worktree
    main: ./main.go
    binary: worktree
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.FullCommit}}
      - -X main.date={{.Date}}

archives:
  - id: worktree
    ids: [worktree]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: liamawhite
    name: worktree
  footer: |
    ## Installation

    ### Download Binary

    Choose the appropriate binary for your platform from the assets below:

    #### Linux (x86_64)
    ```bash
    curl -L https://github.com/liamawhite/worktree/releases/download/{{ .Tag }}/worktree_Linux_x86_64.tar.gz | tar xz
    chmod +x worktree
    sudo mv worktree /usr/local/bin/
    ```

    #### Linux (ARM64)
    ```bash
    curl -L https://github.com/liamawhite/worktree/releases/download/{{ .Tag }}/worktree_Linux_arm64.tar.gz | tar xz
    chmod +x worktree
    sudo mv worktree /usr/local/bin/
    ```

    #### macOS (Intel)
    ```bash
    curl -L https://github.com/liamawhite/worktree/releases/download/{{ .Tag }}/worktree_Darwin_x86_64.tar.gz | tar xz
    chmod +x worktree
    sudo mv worktree /usr/local/bin/
    ```

    #### macOS (Apple Silicon)
    ```bash
    curl -L https://github.com/liamawhite/worktree/releases/download/{{ .Tag }}/worktree_Darwin_arm64.tar.gz | tar xz
    chmod +x worktree
    sudo mv worktree /usr/local/bin/
    ```

    ### Verify Installation
    ```bash
    worktree --version
    ```

    ### Optional: Shell Integration for Directory Switching

    To enable automatic directory changes when using `worktree add` and `worktree switch` commands, add this function to your shell profile:

    (`~/.bashrc`, `~/.bash_profile`, `~/.zshrc`):
    ```bash
    worktree() {
        local cmd="$1"
        
        # Commands that should change directory
        if [[ "$cmd" == "add" || "$cmd" == "switch" || "$cmd" == "sw" ]]; then
            # Capture stderr to look for WT_CHDIR while preserving stdout and interactive TUI
            local temp_file
            temp_file=$(mktemp)
            
            # Run command with stderr redirected to temp file
            command worktree "$@" 2> >(tee "$temp_file" >&2)
            local exit_code=$?
            
            # Look for directory change indicator in stderr
            local target_dir
            target_dir=$(grep "^WT_CHDIR:" "$temp_file" 2>/dev/null | sed 's/^WT_CHDIR://')
            
            # Clean up temp file
            rm -f "$temp_file"
            
            # Change directory if target was specified
            if [[ -n "$target_dir" && -d "$target_dir" ]]; then
                cd "$target_dir" || echo "Warning: Failed to change to directory: $target_dir"
            fi
            
            return $exit_code
        else
            # For all other commands, just run normally
            command worktree "$@"
        fi
    }
    ```
    After adding this function and restarting your shell (or running `source ~/.bashrc`/`source ~/.zshrc`), the `worktree add` and `worktree switch` commands will automatically change your current directory to the worktree location.

    ### Verification with Checksums
    Download `checksums.txt` and verify your binary:
    ```bash
    sha256sum -c checksums.txt
    ```

    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
